import 'package:flutter/material.dart';

import 'accessibility_modes.dart';

@immutable
class AppColors extends ThemeExtension<AppColors> {
  const AppColors({
    required this.primary,
    required this.primaryLight,
    required this.primaryDark,
    required this.accent,
    required this.background,
    required this.surface,
    required this.surfaceLight,
    required this.surfaceMuted,
    required this.textPrimary,
    required this.textSecondary,
    required this.textLight,
    required this.textDark,
    required this.textSubtle,
    required this.success,
    required this.warning,
    required this.error,
    required this.info,
    required this.categoryBlue,
    required this.categoryBlueBg,
    required this.categoryGreen,
    required this.categoryGreenBg,
    required this.categoryPurple,
    required this.categoryPurpleBg,
    required this.categoryOrange,
    required this.categoryOrangeBg,
    required this.categoryIndigo,
    required this.categoryIndigoBg,
    required this.border,
    required this.divider,
    required this.testIconBackground,
    required this.testIconColor,
    required this.testDark,
    required this.warningDark,
    required this.successDark,
    required this.successTint,
    required this.successBgLight,
    required this.infoTint,
    required this.overlayBlueLight,
    required this.warningLight,
    required this.warningBg,
    required this.warningBorder,
    required this.indigoTint,
    required this.errorBg,
    required this.medicalTestSurface,
    required this.medicalTestSurfaceMuted,
    required this.medicalCriticalText,
    required this.primaryGradient,
    required this.reportGradient,
  });

  final Color primary;
  final Color primaryLight;
  final Color primaryDark;
  final Color accent;
  final Color background;
  final Color surface;
  final Color surfaceLight;
  final Color surfaceMuted;
  final Color textPrimary;
  final Color textSecondary;
  final Color textLight;
  final Color textDark;
  final Color textSubtle;
  final Color success;
  final Color warning;
  final Color error;
  final Color info;
  final Color categoryBlue;
  final Color categoryBlueBg;
  final Color categoryGreen;
  final Color categoryGreenBg;
  final Color categoryPurple;
  final Color categoryPurpleBg;
  final Color categoryOrange;
  final Color categoryOrangeBg;
  final Color categoryIndigo;
  final Color categoryIndigoBg;
  final Color border;
  final Color divider;
  final Color testIconBackground;
  final Color testIconColor;
  final Color testDark;
  final Color warningDark;
  final Color successDark;
  final Color successTint;
  final Color successBgLight;
  final Color infoTint;
  final Color overlayBlueLight;
  final Color warningLight;
  final Color warningBg;
  final Color warningBorder;
  final Color indigoTint;
  final Color errorBg;
  final Color medicalTestSurface;
  final Color medicalTestSurfaceMuted;
  final Color medicalCriticalText;
  final LinearGradient primaryGradient;
  final LinearGradient reportGradient;

  @override
  AppColors copyWith({
    Color? primary,
    Color? primaryLight,
    Color? primaryDark,
    Color? accent,
    Color? background,
    Color? surface,
    Color? surfaceLight,
    Color? surfaceMuted,
    Color? textPrimary,
    Color? textSecondary,
    Color? textLight,
    Color? textDark,
    Color? textSubtle,
    Color? success,
    Color? warning,
    Color? error,
    Color? info,
    Color? categoryBlue,
    Color? categoryBlueBg,
    Color? categoryGreen,
    Color? categoryGreenBg,
    Color? categoryPurple,
    Color? categoryPurpleBg,
    Color? categoryOrange,
    Color? categoryOrangeBg,
    Color? categoryIndigo,
    Color? categoryIndigoBg,
    Color? border,
    Color? divider,
    Color? testIconBackground,
    Color? testIconColor,
    Color? testDark,
    Color? warningDark,
    Color? successDark,
    Color? successTint,
    Color? successBgLight,
    Color? infoTint,
    Color? overlayBlueLight,
    Color? warningLight,
    Color? warningBg,
    Color? warningBorder,
    Color? indigoTint,
    Color? errorBg,
    Color? medicalTestSurface,
    Color? medicalTestSurfaceMuted,
    Color? medicalCriticalText,
    LinearGradient? primaryGradient,
    LinearGradient? reportGradient,
  }) {
    return AppColors(
      primary: primary ?? this.primary,
      primaryLight: primaryLight ?? this.primaryLight,
      primaryDark: primaryDark ?? this.primaryDark,
      accent: accent ?? this.accent,
      background: background ?? this.background,
      surface: surface ?? this.surface,
      surfaceLight: surfaceLight ?? this.surfaceLight,
      surfaceMuted: surfaceMuted ?? this.surfaceMuted,
      textPrimary: textPrimary ?? this.textPrimary,
      textSecondary: textSecondary ?? this.textSecondary,
      textLight: textLight ?? this.textLight,
      textDark: textDark ?? this.textDark,
      textSubtle: textSubtle ?? this.textSubtle,
      success: success ?? this.success,
      warning: warning ?? this.warning,
      error: error ?? this.error,
      info: info ?? this.info,
      categoryBlue: categoryBlue ?? this.categoryBlue,
      categoryBlueBg: categoryBlueBg ?? this.categoryBlueBg,
      categoryGreen: categoryGreen ?? this.categoryGreen,
      categoryGreenBg: categoryGreenBg ?? this.categoryGreenBg,
      categoryPurple: categoryPurple ?? this.categoryPurple,
      categoryPurpleBg: categoryPurpleBg ?? this.categoryPurpleBg,
      categoryOrange: categoryOrange ?? this.categoryOrange,
      categoryOrangeBg: categoryOrangeBg ?? this.categoryOrangeBg,
      categoryIndigo: categoryIndigo ?? this.categoryIndigo,
      categoryIndigoBg: categoryIndigoBg ?? this.categoryIndigoBg,
      border: border ?? this.border,
      divider: divider ?? this.divider,
      testIconBackground: testIconBackground ?? this.testIconBackground,
      testIconColor: testIconColor ?? this.testIconColor,
      testDark: testDark ?? this.testDark,
      warningDark: warningDark ?? this.warningDark,
      successDark: successDark ?? this.successDark,
      successTint: successTint ?? this.successTint,
      successBgLight: successBgLight ?? this.successBgLight,
      infoTint: infoTint ?? this.infoTint,
      overlayBlueLight: overlayBlueLight ?? this.overlayBlueLight,
      warningLight: warningLight ?? this.warningLight,
      warningBg: warningBg ?? this.warningBg,
      warningBorder: warningBorder ?? this.warningBorder,
      indigoTint: indigoTint ?? this.indigoTint,
      errorBg: errorBg ?? this.errorBg,
      medicalTestSurface: medicalTestSurface ?? this.medicalTestSurface,
      medicalTestSurfaceMuted:
          medicalTestSurfaceMuted ?? this.medicalTestSurfaceMuted,
      medicalCriticalText: medicalCriticalText ?? this.medicalCriticalText,
      primaryGradient: primaryGradient ?? this.primaryGradient,
      reportGradient: reportGradient ?? this.reportGradient,
    );
  }

  @override
  AppColors lerp(ThemeExtension<AppColors>? other, double t) {
    if (other is! AppColors) {
      return this;
    }

    return AppColors(
      primary: Color.lerp(primary, other.primary, t)!,
      primaryLight: Color.lerp(primaryLight, other.primaryLight, t)!,
      primaryDark: Color.lerp(primaryDark, other.primaryDark, t)!,
      accent: Color.lerp(accent, other.accent, t)!,
      background: Color.lerp(background, other.background, t)!,
      surface: Color.lerp(surface, other.surface, t)!,
      surfaceLight: Color.lerp(surfaceLight, other.surfaceLight, t)!,
      surfaceMuted: Color.lerp(surfaceMuted, other.surfaceMuted, t)!,
      textPrimary: Color.lerp(textPrimary, other.textPrimary, t)!,
      textSecondary: Color.lerp(textSecondary, other.textSecondary, t)!,
      textLight: Color.lerp(textLight, other.textLight, t)!,
      textDark: Color.lerp(textDark, other.textDark, t)!,
      textSubtle: Color.lerp(textSubtle, other.textSubtle, t)!,
      success: Color.lerp(success, other.success, t)!,
      warning: Color.lerp(warning, other.warning, t)!,
      error: Color.lerp(error, other.error, t)!,
      info: Color.lerp(info, other.info, t)!,
      categoryBlue: Color.lerp(categoryBlue, other.categoryBlue, t)!,
      categoryBlueBg: Color.lerp(categoryBlueBg, other.categoryBlueBg, t)!,
      categoryGreen: Color.lerp(categoryGreen, other.categoryGreen, t)!,
      categoryGreenBg: Color.lerp(categoryGreenBg, other.categoryGreenBg, t)!,
      categoryPurple: Color.lerp(categoryPurple, other.categoryPurple, t)!,
      categoryPurpleBg: Color.lerp(
        categoryPurpleBg,
        other.categoryPurpleBg,
        t,
      )!,
      categoryOrange: Color.lerp(categoryOrange, other.categoryOrange, t)!,
      categoryOrangeBg: Color.lerp(
        categoryOrangeBg,
        other.categoryOrangeBg,
        t,
      )!,
      categoryIndigo: Color.lerp(categoryIndigo, other.categoryIndigo, t)!,
      categoryIndigoBg: Color.lerp(
        categoryIndigoBg,
        other.categoryIndigoBg,
        t,
      )!,
      border: Color.lerp(border, other.border, t)!,
      divider: Color.lerp(divider, other.divider, t)!,
      testIconBackground: Color.lerp(
        testIconBackground,
        other.testIconBackground,
        t,
      )!,
      testIconColor: Color.lerp(testIconColor, other.testIconColor, t)!,
      testDark: Color.lerp(testDark, other.testDark, t)!,
      warningDark: Color.lerp(warningDark, other.warningDark, t)!,
      successDark: Color.lerp(successDark, other.successDark, t)!,
      successTint: Color.lerp(successTint, other.successTint, t)!,
      successBgLight: Color.lerp(successBgLight, other.successBgLight, t)!,
      infoTint: Color.lerp(infoTint, other.infoTint, t)!,
      overlayBlueLight: Color.lerp(
        overlayBlueLight,
        other.overlayBlueLight,
        t,
      )!,
      warningLight: Color.lerp(warningLight, other.warningLight, t)!,
      warningBg: Color.lerp(warningBg, other.warningBg, t)!,
      warningBorder: Color.lerp(warningBorder, other.warningBorder, t)!,
      indigoTint: Color.lerp(indigoTint, other.indigoTint, t)!,
      errorBg: Color.lerp(errorBg, other.errorBg, t)!,
      medicalTestSurface: Color.lerp(
        medicalTestSurface,
        other.medicalTestSurface,
        t,
      )!,
      medicalTestSurfaceMuted: Color.lerp(
        medicalTestSurfaceMuted,
        other.medicalTestSurfaceMuted,
        t,
      )!,
      medicalCriticalText: Color.lerp(
        medicalCriticalText,
        other.medicalCriticalText,
        t,
      )!,
      primaryGradient: LinearGradient.lerp(
        primaryGradient,
        other.primaryGradient,
        t,
      )!,
      reportGradient: LinearGradient.lerp(
        reportGradient,
        other.reportGradient,
        t,
      )!,
    );
  }
}

class AppPaletteResolver {
  AppPaletteResolver._();

  static AppColors resolve({
    required Brightness brightness,
    required AccessibilityMode accessibilityMode,
  }) {
    return switch ((brightness, accessibilityMode)) {
      (Brightness.dark, AccessibilityMode.protanopia) => _darkProtanopia,
      (Brightness.dark, AccessibilityMode.deuteranopia) => _darkDeuteranopia,
      (Brightness.dark, AccessibilityMode.tritanopia) => _darkTritanopia,
      (Brightness.dark, _) => _darkStandard,
      (Brightness.light, AccessibilityMode.protanopia) => _lightProtanopia,
      (Brightness.light, AccessibilityMode.deuteranopia) => _lightDeuteranopia,
      (Brightness.light, AccessibilityMode.tritanopia) => _lightTritanopia,
      _ => _lightStandard,
    };
  }

  static const _lightStandard = AppColors(
    primary: Color(0xFF4F46E5),
    primaryLight: Color(0xFF818CF8),
    primaryDark: Color(0xFF3730A3),
    accent: Color(0xFF6366F1),
    background: Color(0xFFF4F6FA),
    surface: Colors.white,
    surfaceLight: Color(0xFFF9FAFB),
    surfaceMuted: Color(0xFFF3F4F6),
    textPrimary: Color(0xFF111827),
    textSecondary: Color(0xFF6B7280),
    textLight: Color(0xFF9CA3AF),
    textDark: Color(0xFF1F2937),
    textSubtle: Color(0xFF4B5563),
    success: Color(0xFF10B981),
    warning: Color(0xFFF59E0B),
    error: Color(0xFFEF4444),
    info: Color(0xFF3B82F6),
    categoryBlue: Color(0xFF3B82F6),
    categoryBlueBg: Color(0xFFEFF6FF),
    categoryGreen: Color(0xFF10B981),
    categoryGreenBg: Color(0xFFECFDF5),
    categoryPurple: Color(0xFF8B5CF6),
    categoryPurpleBg: Color(0xFFFAF5FF),
    categoryOrange: Color(0xFFF97316),
    categoryOrangeBg: Color(0xFFFFF7ED),
    categoryIndigo: Color(0xFF6366F1),
    categoryIndigoBg: Color(0xFFEEF2FF),
    border: Color(0xFFE5E7EB),
    divider: Color(0xFFE5E7EB),
    testIconBackground: Color(0xFFEEF2FF),
    testIconColor: Color(0xFF4F46E5),
    testDark: Color(0xFF1A1A2E),
    warningDark: Color(0xFF92400E),
    successDark: Color(0xFF059669),
    successTint: Color(0xFFD1FAE5),
    successBgLight: Color(0xFFF0FDF4),
    infoTint: Color(0xFFDBEAFE),
    overlayBlueLight: Color(0xFFBFDBFE),
    warningLight: Color(0xFFFBBF24),
    warningBg: Color(0xFFFFFBEB),
    warningBorder: Color(0xFFFDE68A),
    indigoTint: Color(0xFFEDE9FE),
    errorBg: Color(0xFFFEF2F2),
    medicalTestSurface: Color(0xFFF7F8FC),
    medicalTestSurfaceMuted: Color(0xFFEFF2F8),
    medicalCriticalText: Color(0xFF7F1D1D),
    primaryGradient: LinearGradient(
      colors: [Color(0xFF667EEA), Color(0xFF764BA2)],
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
    ),
    reportGradient: LinearGradient(
      colors: [Color(0xFF667EEA), Color(0xFF764BA2)],
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
    ),
  );

  static const _lightProtanopia = AppColors(
    primary: Color(0xFF0057B8),
    primaryLight: Color(0xFF4A88E8),
    primaryDark: Color(0xFF0B3D91),
    accent: Color(0xFF7C3AED),
    background: Color(0xFFF4F7FB),
    surface: Colors.white,
    surfaceLight: Color(0xFFF8FAFD),
    surfaceMuted: Color(0xFFF1F5F9),
    textPrimary: Color(0xFF0F172A),
    textSecondary: Color(0xFF475569),
    textLight: Color(0xFF94A3B8),
    textDark: Color(0xFF1E293B),
    textSubtle: Color(0xFF334155),
    success: Color(0xFF0284C7),
    warning: Color(0xFFB45309),
    error: Color(0xFF7C3AED),
    info: Color(0xFF0057B8),
    categoryBlue: Color(0xFF0057B8),
    categoryBlueBg: Color(0xFFE7F0FF),
    categoryGreen: Color(0xFF0284C7),
    categoryGreenBg: Color(0xFFE0F2FE),
    categoryPurple: Color(0xFF7C3AED),
    categoryPurpleBg: Color(0xFFF3E8FF),
    categoryOrange: Color(0xFFB45309),
    categoryOrangeBg: Color(0xFFFFF1E6),
    categoryIndigo: Color(0xFF1D4ED8),
    categoryIndigoBg: Color(0xFFEBF2FF),
    border: Color(0xFFD7DEE8),
    divider: Color(0xFFD7DEE8),
    testIconBackground: Color(0xFFE7F0FF),
    testIconColor: Color(0xFF0057B8),
    testDark: Color(0xFF101827),
    warningDark: Color(0xFF9A3412),
    successDark: Color(0xFF0369A1),
    successTint: Color(0xFFE0F2FE),
    successBgLight: Color(0xFFF0F9FF),
    infoTint: Color(0xFFDBEAFE),
    overlayBlueLight: Color(0xFFBFDBFE),
    warningLight: Color(0xFFF59E0B),
    warningBg: Color(0xFFFFF7ED),
    warningBorder: Color(0xFFFCD34D),
    indigoTint: Color(0xFFEDE9FE),
    errorBg: Color(0xFFF3E8FF),
    medicalTestSurface: Color(0xFFF6F8FC),
    medicalTestSurfaceMuted: Color(0xFFEEF2F7),
    medicalCriticalText: Color(0xFF5B21B6),
    primaryGradient: LinearGradient(
      colors: [Color(0xFF0057B8), Color(0xFF7C3AED)],
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
    ),
    reportGradient: LinearGradient(
      colors: [Color(0xFF0057B8), Color(0xFF7C3AED)],
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
    ),
  );

  static const _lightDeuteranopia = AppColors(
    primary: Color(0xFF0F62FE),
    primaryLight: Color(0xFF5B8CFF),
    primaryDark: Color(0xFF003A9C),
    accent: Color(0xFF9333EA),
    background: Color(0xFFF5F7FB),
    surface: Colors.white,
    surfaceLight: Color(0xFFF8FAFC),
    surfaceMuted: Color(0xFFF1F5F9),
    textPrimary: Color(0xFF111827),
    textSecondary: Color(0xFF475569),
    textLight: Color(0xFF94A3B8),
    textDark: Color(0xFF1E293B),
    textSubtle: Color(0xFF334155),
    success: Color(0xFF2563EB),
    warning: Color(0xFFD97706),
    error: Color(0xFFBE185D),
    info: Color(0xFF0F62FE),
    categoryBlue: Color(0xFF0F62FE),
    categoryBlueBg: Color(0xFFE8F0FF),
    categoryGreen: Color(0xFF2563EB),
    categoryGreenBg: Color(0xFFEFF6FF),
    categoryPurple: Color(0xFF9333EA),
    categoryPurpleBg: Color(0xFFF3E8FF),
    categoryOrange: Color(0xFFD97706),
    categoryOrangeBg: Color(0xFFFFF4E5),
    categoryIndigo: Color(0xFF4338CA),
    categoryIndigoBg: Color(0xFFEEF2FF),
    border: Color(0xFFD7DEE8),
    divider: Color(0xFFD7DEE8),
    testIconBackground: Color(0xFFE8F0FF),
    testIconColor: Color(0xFF0F62FE),
    testDark: Color(0xFF101827),
    warningDark: Color(0xFF9A3412),
    successDark: Color(0xFF1D4ED8),
    successTint: Color(0xFFDBEAFE),
    successBgLight: Color(0xFFEFF6FF),
    infoTint: Color(0xFFDBEAFE),
    overlayBlueLight: Color(0xFFBFDBFE),
    warningLight: Color(0xFFF59E0B),
    warningBg: Color(0xFFFFF7ED),
    warningBorder: Color(0xFFFCD34D),
    indigoTint: Color(0xFFEDE9FE),
    errorBg: Color(0xFFFCE7F3),
    medicalTestSurface: Color(0xFFF7F8FC),
    medicalTestSurfaceMuted: Color(0xFFF0F4F8),
    medicalCriticalText: Color(0xFF9D174D),
    primaryGradient: LinearGradient(
      colors: [Color(0xFF0F62FE), Color(0xFF9333EA)],
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
    ),
    reportGradient: LinearGradient(
      colors: [Color(0xFF0F62FE), Color(0xFF9333EA)],
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
    ),
  );

  static const _lightTritanopia = AppColors(
    primary: Color(0xFF006D77),
    primaryLight: Color(0xFF2A9D8F),
    primaryDark: Color(0xFF0B525B),
    accent: Color(0xFFB56576),
    background: Color(0xFFF6F8FB),
    surface: Colors.white,
    surfaceLight: Color(0xFFF8FAFC),
    surfaceMuted: Color(0xFFF1F5F9),
    textPrimary: Color(0xFF111827),
    textSecondary: Color(0xFF475569),
    textLight: Color(0xFF94A3B8),
    textDark: Color(0xFF1E293B),
    textSubtle: Color(0xFF334155),
    success: Color(0xFF2A9D8F),
    warning: Color(0xFFE76F51),
    error: Color(0xFFB56576),
    info: Color(0xFF006D77),
    categoryBlue: Color(0xFF006D77),
    categoryBlueBg: Color(0xFFE6F4F5),
    categoryGreen: Color(0xFF2A9D8F),
    categoryGreenBg: Color(0xFFE8F8F5),
    categoryPurple: Color(0xFFB56576),
    categoryPurpleBg: Color(0xFFF9ECEF),
    categoryOrange: Color(0xFFE76F51),
    categoryOrangeBg: Color(0xFFFFF1EC),
    categoryIndigo: Color(0xFF8D5A97),
    categoryIndigoBg: Color(0xFFF4ECF6),
    border: Color(0xFFD7DEE8),
    divider: Color(0xFFD7DEE8),
    testIconBackground: Color(0xFFE6F4F5),
    testIconColor: Color(0xFF006D77),
    testDark: Color(0xFF0E1A20),
    warningDark: Color(0xFF9A3412),
    successDark: Color(0xFF1D7874),
    successTint: Color(0xFFD7F3EE),
    successBgLight: Color(0xFFF1FBF9),
    infoTint: Color(0xFFCCEDEE),
    overlayBlueLight: Color(0xFFBEE3E5),
    warningLight: Color(0xFFF4A261),
    warningBg: Color(0xFFFFF2EC),
    warningBorder: Color(0xFFF5C6B5),
    indigoTint: Color(0xFFF4ECF6),
    errorBg: Color(0xFFF9ECEF),
    medicalTestSurface: Color(0xFFF7F9FB),
    medicalTestSurfaceMuted: Color(0xFFEFF4F6),
    medicalCriticalText: Color(0xFF8B3D52),
    primaryGradient: LinearGradient(
      colors: [Color(0xFF006D77), Color(0xFFB56576)],
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
    ),
    reportGradient: LinearGradient(
      colors: [Color(0xFF006D77), Color(0xFFB56576)],
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
    ),
  );

  static const _darkStandard = AppColors(
    primary: Color(0xFF8B83FF),
    primaryLight: Color(0xFFA7A1FF),
    primaryDark: Color(0xFF5951D8),
    accent: Color(0xFF9B95FF),
    background: Color(0xFF0F172A),
    surface: Color(0xFF111827),
    surfaceLight: Color(0xFF1F2937),
    surfaceMuted: Color(0xFF1F2937),
    textPrimary: Color(0xFFF8FAFC),
    textSecondary: Color(0xFFCBD5E1),
    textLight: Color(0xFF94A3B8),
    textDark: Color(0xFFE2E8F0),
    textSubtle: Color(0xFFCBD5E1),
    success: Color(0xFF34D399),
    warning: Color(0xFFFBBF24),
    error: Color(0xFFFB7185),
    info: Color(0xFF60A5FA),
    categoryBlue: Color(0xFF60A5FA),
    categoryBlueBg: Color(0xFF172554),
    categoryGreen: Color(0xFF34D399),
    categoryGreenBg: Color(0xFF052E2B),
    categoryPurple: Color(0xFFC084FC),
    categoryPurpleBg: Color(0xFF3B0764),
    categoryOrange: Color(0xFFFB923C),
    categoryOrangeBg: Color(0xFF431407),
    categoryIndigo: Color(0xFFA5B4FC),
    categoryIndigoBg: Color(0xFF1E1B4B),
    border: Color(0xFF334155),
    divider: Color(0xFF334155),
    testIconBackground: Color(0xFF1E1B4B),
    testIconColor: Color(0xFFA5B4FC),
    testDark: Color(0xFF111827),
    warningDark: Color(0xFFFDE68A),
    successDark: Color(0xFF6EE7B7),
    successTint: Color(0xFF064E3B),
    successBgLight: Color(0xFF052E2B),
    infoTint: Color(0xFF1D4ED8),
    overlayBlueLight: Color(0xFF1E3A8A),
    warningLight: Color(0xFFFCD34D),
    warningBg: Color(0xFF451A03),
    warningBorder: Color(0xFF92400E),
    indigoTint: Color(0xFF312E81),
    errorBg: Color(0xFF4C0519),
    medicalTestSurface: Color(0xFF162033),
    medicalTestSurfaceMuted: Color(0xFF1C2940),
    medicalCriticalText: Color(0xFFFDA4AF),
    primaryGradient: LinearGradient(
      colors: [Color(0xFF5B5BD6), Color(0xFF8B5CF6)],
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
    ),
    reportGradient: LinearGradient(
      colors: [Color(0xFF5B5BD6), Color(0xFF8B5CF6)],
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
    ),
  );

  static const _darkProtanopia = AppColors(
    primary: Color(0xFF6FA8FF),
    primaryLight: Color(0xFF9CC4FF),
    primaryDark: Color(0xFF2E6FCC),
    accent: Color(0xFFC084FC),
    background: Color(0xFF0B1220),
    surface: Color(0xFF111827),
    surfaceLight: Color(0xFF1E293B),
    surfaceMuted: Color(0xFF1F2937),
    textPrimary: Color(0xFFF8FAFC),
    textSecondary: Color(0xFFD6E0EA),
    textLight: Color(0xFF94A3B8),
    textDark: Color(0xFFE2E8F0),
    textSubtle: Color(0xFFCBD5E1),
    success: Color(0xFF38BDF8),
    warning: Color(0xFFFBBF24),
    error: Color(0xFFC084FC),
    info: Color(0xFF6FA8FF),
    categoryBlue: Color(0xFF6FA8FF),
    categoryBlueBg: Color(0xFF13233E),
    categoryGreen: Color(0xFF38BDF8),
    categoryGreenBg: Color(0xFF0C3148),
    categoryPurple: Color(0xFFC084FC),
    categoryPurpleBg: Color(0xFF3B1D57),
    categoryOrange: Color(0xFFFBBF24),
    categoryOrangeBg: Color(0xFF4A2B05),
    categoryIndigo: Color(0xFF93C5FD),
    categoryIndigoBg: Color(0xFF1D3557),
    border: Color(0xFF334155),
    divider: Color(0xFF334155),
    testIconBackground: Color(0xFF13233E),
    testIconColor: Color(0xFF6FA8FF),
    testDark: Color(0xFF111827),
    warningDark: Color(0xFFFCD34D),
    successDark: Color(0xFF7DD3FC),
    successTint: Color(0xFF164E63),
    successBgLight: Color(0xFF12363A),
    infoTint: Color(0xFF1D4ED8),
    overlayBlueLight: Color(0xFF1E3A8A),
    warningLight: Color(0xFFFDE68A),
    warningBg: Color(0xFF4A2B05),
    warningBorder: Color(0xFFB45309),
    indigoTint: Color(0xFF1D3557),
    errorBg: Color(0xFF3B1D57),
    medicalTestSurface: Color(0xFF162033),
    medicalTestSurfaceMuted: Color(0xFF1B2840),
    medicalCriticalText: Color(0xFFE9D5FF),
    primaryGradient: LinearGradient(
      colors: [Color(0xFF1D4ED8), Color(0xFF7C3AED)],
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
    ),
    reportGradient: LinearGradient(
      colors: [Color(0xFF1D4ED8), Color(0xFF7C3AED)],
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
    ),
  );

  static const _darkDeuteranopia = AppColors(
    primary: Color(0xFF7CB4FF),
    primaryLight: Color(0xFFA5CBFF),
    primaryDark: Color(0xFF3E78D4),
    accent: Color(0xFFE879F9),
    background: Color(0xFF0C1320),
    surface: Color(0xFF111827),
    surfaceLight: Color(0xFF1E293B),
    surfaceMuted: Color(0xFF1F2937),
    textPrimary: Color(0xFFF8FAFC),
    textSecondary: Color(0xFFD6E0EA),
    textLight: Color(0xFF94A3B8),
    textDark: Color(0xFFE2E8F0),
    textSubtle: Color(0xFFCBD5E1),
    success: Color(0xFF60A5FA),
    warning: Color(0xFFF59E0B),
    error: Color(0xFFF472B6),
    info: Color(0xFF7CB4FF),
    categoryBlue: Color(0xFF7CB4FF),
    categoryBlueBg: Color(0xFF14233E),
    categoryGreen: Color(0xFF60A5FA),
    categoryGreenBg: Color(0xFF122A46),
    categoryPurple: Color(0xFFE879F9),
    categoryPurpleBg: Color(0xFF471A54),
    categoryOrange: Color(0xFFF59E0B),
    categoryOrangeBg: Color(0xFF492A06),
    categoryIndigo: Color(0xFF93C5FD),
    categoryIndigoBg: Color(0xFF1D3557),
    border: Color(0xFF334155),
    divider: Color(0xFF334155),
    testIconBackground: Color(0xFF14233E),
    testIconColor: Color(0xFF7CB4FF),
    testDark: Color(0xFF111827),
    warningDark: Color(0xFFFCD34D),
    successDark: Color(0xFFBFDBFE),
    successTint: Color(0xFF1E3A8A),
    successBgLight: Color(0xFF122A46),
    infoTint: Color(0xFF1D4ED8),
    overlayBlueLight: Color(0xFF1E3A8A),
    warningLight: Color(0xFFFCD34D),
    warningBg: Color(0xFF492A06),
    warningBorder: Color(0xFFB45309),
    indigoTint: Color(0xFF1D3557),
    errorBg: Color(0xFF471A54),
    medicalTestSurface: Color(0xFF172236),
    medicalTestSurfaceMuted: Color(0xFF1D2A41),
    medicalCriticalText: Color(0xFFF5D0FE),
    primaryGradient: LinearGradient(
      colors: [Color(0xFF2563EB), Color(0xFFE879F9)],
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
    ),
    reportGradient: LinearGradient(
      colors: [Color(0xFF2563EB), Color(0xFFE879F9)],
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
    ),
  );

  static const _darkTritanopia = AppColors(
    primary: Color(0xFF5EEAD4),
    primaryLight: Color(0xFF99F6E4),
    primaryDark: Color(0xFF0F766E),
    accent: Color(0xFFFCA5A5),
    background: Color(0xFF0C131B),
    surface: Color(0xFF111827),
    surfaceLight: Color(0xFF1E293B),
    surfaceMuted: Color(0xFF1F2937),
    textPrimary: Color(0xFFF8FAFC),
    textSecondary: Color(0xFFD6E0EA),
    textLight: Color(0xFF94A3B8),
    textDark: Color(0xFFE2E8F0),
    textSubtle: Color(0xFFCBD5E1),
    success: Color(0xFF5EEAD4),
    warning: Color(0xFFFDA4AF),
    error: Color(0xFFF97316),
    info: Color(0xFF5EEAD4),
    categoryBlue: Color(0xFF5EEAD4),
    categoryBlueBg: Color(0xFF11353B),
    categoryGreen: Color(0xFF2DD4BF),
    categoryGreenBg: Color(0xFF11353B),
    categoryPurple: Color(0xFFFCA5A5),
    categoryPurpleBg: Color(0xFF45252A),
    categoryOrange: Color(0xFFF97316),
    categoryOrangeBg: Color(0xFF4A260A),
    categoryIndigo: Color(0xFFF9A8D4),
    categoryIndigoBg: Color(0xFF4A2237),
    border: Color(0xFF334155),
    divider: Color(0xFF334155),
    testIconBackground: Color(0xFF11353B),
    testIconColor: Color(0xFF5EEAD4),
    testDark: Color(0xFF101722),
    warningDark: Color(0xFFFECACA),
    successDark: Color(0xFF99F6E4),
    successTint: Color(0xFF134E4A),
    successBgLight: Color(0xFF11353B),
    infoTint: Color(0xFF164E63),
    overlayBlueLight: Color(0xFF115E59),
    warningLight: Color(0xFFFDA4AF),
    warningBg: Color(0xFF4A260A),
    warningBorder: Color(0xFFEA580C),
    indigoTint: Color(0xFF4A2237),
    errorBg: Color(0xFF4A260A),
    medicalTestSurface: Color(0xFF17242B),
    medicalTestSurfaceMuted: Color(0xFF1C2A33),
    medicalCriticalText: Color(0xFFFED7AA),
    primaryGradient: LinearGradient(
      colors: [Color(0xFF0F766E), Color(0xFFEA580C)],
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
    ),
    reportGradient: LinearGradient(
      colors: [Color(0xFF0F766E), Color(0xFFEA580C)],
      begin: Alignment.topLeft,
      end: Alignment.bottomRight,
    ),
  );
}

extension AppThemeContext on BuildContext {
  AppColors get appColors => Theme.of(this).extension<AppColors>()!;
}
