"""initial

Revision ID: 0001_initial
Revises: 
Create Date: 2026-05-25 00:00:00.000000
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(length=120), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("sex", sa.String(length=20), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("emergency_contact", sa.String(length=20), nullable=True),
        sa.Column("medical_history", sa.Text(), nullable=True),
        sa.Column("profile_image_url", sa.String(length=500), nullable=True),
        sa.Column("reset_otp", sa.String(length=6), nullable=True),
        sa.Column("reset_otp_expiry", sa.DateTime(), nullable=True),
        sa.Column("consent_given_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.UniqueConstraint("email", name="uq_user_email"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    op.create_index(op.f("ix_user_created_at"), "user", ["created_at"], unique=False)

    op.create_table(
        "auth_rate_limit_events",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("scope_key", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )
    op.create_index(
        op.f("ix_auth_rate_limit_events_created_at"),
        "auth_rate_limit_events",
        ["created_at"],
        unique=False,
    )

    op.create_table(
        "eye_tracking_tests",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("user.id"), nullable=False),
        sa.Column("test_name", sa.String(length=255), nullable=False),
        sa.Column("test_duration", sa.Float(), nullable=False),
        sa.Column("gaze_accuracy", sa.Float(), nullable=True),
        sa.Column("fixation_stability_score", sa.Float(), nullable=True),
        sa.Column("saccade_consistency_score", sa.Float(), nullable=True),
        sa.Column("overall_performance_score", sa.Float(), nullable=True),
        sa.Column("performance_classification", sa.String(length=50), nullable=True),
        sa.Column("left_pupil_metrics", sa.Text(), nullable=True),
        sa.Column("right_pupil_metrics", sa.Text(), nullable=True),
        sa.Column("raw_data", sa.Text(), nullable=True),
        sa.Column("screen_width", sa.Integer(), nullable=True),
        sa.Column("screen_height", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
    )

    op.create_table(
        "visual_acuity_tests",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("user.id"), nullable=False),
        sa.Column("test_variant", sa.String(length=50), nullable=True),
        sa.Column("correct_answers", sa.Integer(), nullable=False),
        sa.Column("total_questions", sa.Integer(), nullable=False),
        sa.Column("logmar_value", sa.Float(), nullable=False),
        sa.Column("snellen_value", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )

    op.create_table(
        "camera_eye_tracking_sessions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("user.id"), nullable=False),
        sa.Column("session_name", sa.String(length=255), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("total_blinks", sa.Integer(), nullable=True),
        sa.Column("blink_rate_per_minute", sa.Float(), nullable=True),
        sa.Column("left_eye_ear_mean", sa.Float(), nullable=True),
        sa.Column("left_eye_ear_std", sa.Float(), nullable=True),
        sa.Column("left_eye_ear_min", sa.Float(), nullable=True),
        sa.Column("left_eye_ear_max", sa.Float(), nullable=True),
        sa.Column("right_eye_ear_mean", sa.Float(), nullable=True),
        sa.Column("right_eye_ear_std", sa.Float(), nullable=True),
        sa.Column("right_eye_ear_min", sa.Float(), nullable=True),
        sa.Column("right_eye_ear_max", sa.Float(), nullable=True),
        sa.Column("average_ear_mean", sa.Float(), nullable=True),
        sa.Column("average_ear_std", sa.Float(), nullable=True),
        sa.Column("average_ear_min", sa.Float(), nullable=True),
        sa.Column("average_ear_max", sa.Float(), nullable=True),
        sa.Column("gaze_distribution", sa.Text(), nullable=True),
        sa.Column("total_frames", sa.Integer(), nullable=True),
        sa.Column("frames_with_face", sa.Integer(), nullable=True),
        sa.Column("detection_rate", sa.Float(), nullable=True),
        sa.Column("blink_events", sa.Text(), nullable=True),
        sa.Column("gaze_events", sa.Text(), nullable=True),
        sa.Column("camera_id", sa.Integer(), nullable=True),
        sa.Column("ear_threshold", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
    )

    op.create_table(
        "colour_vision_tests",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("user.id"), nullable=False),
        sa.Column("total_plates", sa.Integer(), nullable=False),
        sa.Column("plate_ids", sa.Text(), nullable=False),
        sa.Column("plate_images", sa.Text(), nullable=False),
        sa.Column("user_answers", sa.Text(), nullable=False),
        sa.Column("correct_answers", sa.Text(), nullable=False),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("test_duration", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
    )

    op.create_table(
        "blink_fatigue_tests",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("user.id"), nullable=False),
        sa.Column("prediction", sa.String(length=50), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("drowsy_probability", sa.Float(), nullable=False),
        sa.Column("notdrowsy_probability", sa.Float(), nullable=False),
        sa.Column("fatigue_level", sa.String(length=100), nullable=False),
        sa.Column("alert_triggered", sa.Boolean(), nullable=True),
        sa.Column("test_duration", sa.Float(), nullable=True),
        sa.Column("image_filename", sa.String(length=255), nullable=True),
        sa.Column("total_blinks", sa.Integer(), nullable=True),
        sa.Column("avg_blinks_per_minute", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
    )

    op.create_table(
        "distance_calibrations",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("user.id"), nullable=False),
        sa.Column("calibrated_at", sa.DateTime(), nullable=False),
        sa.Column("reference_distance", sa.Float(), nullable=False),
        sa.Column("baseline_ipd_pixels", sa.Float(), nullable=False),
        sa.Column("baseline_face_width_pixels", sa.Float(), nullable=False),
        sa.Column("focal_length", sa.Float(), nullable=False),
        sa.Column("real_world_ipd", sa.Float(), nullable=True),
        sa.Column("tolerance_cm", sa.Float(), nullable=True),
        sa.Column("device_model", sa.String(length=100), nullable=True),
        sa.Column("camera_resolution", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
    )

    op.create_table(
        "pupil_reflex_tests",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("user.id"), nullable=False),
        sa.Column("reaction_time", sa.Float(), nullable=False),
        sa.Column("constriction_amplitude", sa.String(length=50), nullable=True),
        sa.Column("symmetry", sa.String(length=50), nullable=True),
        sa.Column("nystagmus_detected", sa.Boolean(), nullable=True),
        sa.Column("nystagmus_type", sa.String(length=50), nullable=True),
        sa.Column("nystagmus_severity", sa.String(length=50), nullable=True),
        sa.Column("nystagmus_confidence", sa.Float(), nullable=True),
        sa.Column("diagnosis", sa.Text(), nullable=True),
        sa.Column("recommendations", sa.Text(), nullable=True),
        sa.Column("left_pupil_size_before", sa.Float(), nullable=True),
        sa.Column("left_pupil_size_after", sa.Float(), nullable=True),
        sa.Column("right_pupil_size_before", sa.Float(), nullable=True),
        sa.Column("right_pupil_size_after", sa.Float(), nullable=True),
        sa.Column("test_duration", sa.Float(), nullable=True),
        sa.Column("image_filename", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
    )

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("actor_id", sa.Integer(), nullable=False),
        sa.Column("actor_role", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
    )

    op.create_table(
        "clinical_reports",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("patient_id", sa.Integer(), sa.ForeignKey("user.id"), nullable=False),
        sa.Column(
            "visual_acuity_test_id",
            sa.Integer(),
            sa.ForeignKey("visual_acuity_tests.id"),
            nullable=True,
        ),
        sa.Column(
            "colour_vision_test_id",
            sa.Integer(),
            sa.ForeignKey("colour_vision_tests.id"),
            nullable=True,
        ),
        sa.Column(
            "pupil_reflex_test_id",
            sa.Integer(),
            sa.ForeignKey("pupil_reflex_tests.id"),
            nullable=True,
        ),
        sa.Column(
            "blink_fatigue_test_id",
            sa.Integer(),
            sa.ForeignKey("blink_fatigue_tests.id"),
            nullable=True,
        ),
        sa.Column("ai_summary", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("clinician_id", sa.Integer(), nullable=True),
        sa.Column("clinician_notes", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("pdf_path", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("clinical_reports")
    op.drop_table("audit_logs")
    op.drop_table("pupil_reflex_tests")
    op.drop_table("distance_calibrations")
    op.drop_table("blink_fatigue_tests")
    op.drop_table("colour_vision_tests")
    op.drop_table("camera_eye_tracking_sessions")
    op.drop_table("visual_acuity_tests")
    op.drop_table("eye_tracking_tests")
    op.drop_index(op.f("ix_user_created_at"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_table("auth_rate_limit_events")
    # ### end Alembic commands ###
