// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK8Yf5zcFHzSrTnESTgZJsLK0XymNWJmM',
    appId: '1:735051756678:web:b8c3763b65b4d3ce06cd07',
    messagingSenderId: '735051756678',
    projectId: 'netracare-ef30d',
    authDomain: 'netracare-ef30d.firebaseapp.com',
    storageBucket: 'netracare-ef30d.firebasestorage.app',
    measurementId: 'G-4CTY3MV5N1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyDS8zQ4DWHficzysQeSJWs6fgItpzYLE',
    appId: '1:735051756678:android:ff4454e95ad7c74606cd07',
    messagingSenderId: '735051756678',
    projectId: 'netracare-ef30d',
    storageBucket: 'netracare-ef30d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9YELnTkXM4iopB9pduwrE1SLvxAj5Tl0',
    appId: '1:735051756678:ios:1243a5e7107a75a006cd07',
    messagingSenderId: '735051756678',
    projectId: 'netracare-ef30d',
    storageBucket: 'netracare-ef30d.firebasestorage.app',
    androidClientId:
        '735051756678-8ju9d528l0peg62g2nstu45h3btbgb34.apps.googleusercontent.com',
    iosClientId:
        '735051756678-6902mppq99jg5s3qqi0hhjg743ljetg1.apps.googleusercontent.com',
    iosBundleId: 'fyp.netracare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9YELnTkXM4iopB9pduwrE1SLvxAj5Tl0',
    appId: '1:735051756678:ios:1243a5e7107a75a006cd07',
    messagingSenderId: '735051756678',
    projectId: 'netracare-ef30d',
    storageBucket: 'netracare-ef30d.firebasestorage.app',
    androidClientId:
        '735051756678-8ju9d528l0peg62g2nstu45h3btbgb34.apps.googleusercontent.com',
    iosClientId:
        '735051756678-6902mppq99jg5s3qqi0hhjg743ljetg1.apps.googleusercontent.com',
    iosBundleId: 'fyp.netracare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK8Yf5zcFHzSrTnESTgZJsLK0XymNWJmM',
    appId: '1:735051756678:web:d8efc7ec304f5f8006cd07',
    messagingSenderId: '735051756678',
    projectId: 'netracare-ef30d',
    authDomain: 'netracare-ef30d.firebaseapp.com',
    storageBucket: 'netracare-ef30d.firebasestorage.app',
    measurementId: 'G-TMZHG3RQCT',
  );
}
